/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juegoproyecto;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.Timer;

public class SegundaGui extends javax.swing.JFrame {

   private Tablero t;
    private Figura figura;
    private Timer hilo;
    
    public SegundaGui() {
        
        t = new Tablero(24, 12);
        figura = new Figura();
        
        initComponents();
        figura.crearFigura();
        t.agregar(figura);
        control();
    }

    public void imprimeTetris() {
        for (int i = 0; i < t.getTablero().length; i++) {
            for (int j = 0; j < t.getTablero()[0].length; j++) {

                JLabel label = new JLabel();
                label.setOpaque(true);

                if (t.getTablero()[i][j] == 0) {
                    label.setBackground(Color.black);
                } else {

                    label.setBackground(Color.green);

                }
                panel3.add(label);
            }

        }
    }

    public void refrescar() {
        panel3.removeAll();
        imprimeTetris();
        revalidate();
    }

    public void control() {

        hilo = new Timer(1000, new ActionListener() {

            public void actionPerformed(ActionEvent e) {

                //todo lo que ponga aqui se va a repetir la cantidad a milisegundos
                if (t.getCaer()) {   //if (tablero.getCaer()) {
                    System.out.println(t.getCaer());
                    t.desciende(figura);
                    refrescar();
                    System.out.println("PRIMERO");
                } else {
                    hilo.stop();
                    figura.crearFigura();

                    t.agregar(figura);
                    t.setCaer(true);
                    refrescar();
                    control();

                }

            }
        });

        hilo.start();
    }

    {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel3 = new java.awt.Panel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panel3.setLayout(new java.awt.GridLayout(24, 12, 1, 1));
        getContentPane().add(panel3);
        panel3.setBounds(0, 0, 590, 440);

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(871, 62, 230, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SegundaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SegundaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SegundaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SegundaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SegundaGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private java.awt.Panel panel3;
    // End of variables declaration//GEN-END:variables
}
